<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_Select" exclude-result-prefixes=" oracle-xsl-mapper xsi xsd xsl ns0 socket dvm mhdr oraxsl oraext xp20 xref"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Application1/DataBase_TO_File/DB_Select"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/DB_Select.wsdl"/>
            <oracle-xsl-mapper:rootElement name="CreditcardinfoCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_Select"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/DB_Select.wsdl"/>
            <oracle-xsl-mapper:rootElement name="CreditcardinfoCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_Select"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.4.0(XSLT Build 190828.0353.3300) AT [TUE AUG 19 12:32:28 IST 2025].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <ns0:CreditcardinfoCollection>
         <xsl:for-each select="/ns0:CreditcardinfoCollection/ns0:Creditcardinfo">
            <ns0:Creditcardinfo>
               <ns0:ssn>
                  <xsl:value-of select="ns0:ssn"/>
               </ns0:ssn>
               <ns0:firstName>
                  <xsl:value-of select="ns0:firstName"/>
               </ns0:firstName>
               <ns0:lastName>
                  <xsl:value-of select="ns0:lastName"/>
               </ns0:lastName>
               <ns0:ccnumber>
                  <xsl:value-of select="ns0:ccnumber"/>
               </ns0:ccnumber>
               <ns0:creditrating>
                  <xsl:value-of select="ns0:creditrating"/>
               </ns0:creditrating>
               <ns0:status>
                  <xsl:value-of select="ns0:status"/>
               </ns0:status>
               <ns0:accountNo>
                  <xsl:value-of select="ns0:accountNo"/>
               </ns0:accountNo>
               <ns0:bankName>
                  <xsl:value-of select="ns0:bankName"/>
               </ns0:bankName>
            </ns0:Creditcardinfo>
         </xsl:for-each>
      </ns0:CreditcardinfoCollection>
   </xsl:template>
</xsl:stylesheet>
