<wsdl:definitions
     name="DB_Select"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application1/DataBase_TO_File/DB_Select"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Application1/DataBase_TO_File/DB_Select"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_Select"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="DB_Select_plt" >
    <plt:role name="DB_Select_role" >
      <plt:portType name="tns:DB_Select_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_Select" schemaLocation="../Schemas/DB_Select_table.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="DB_SelectSelect_inputParameters">
        <wsdl:part name="DB_SelectSelect_inputParameters" element="top:DB_SelectSelect_ccnbInputParameters"/>
    </wsdl:message>
    <wsdl:message name="CreditcardinfoCollection_msg">
        <wsdl:part name="CreditcardinfoCollection" element="top:CreditcardinfoCollection"/>
    </wsdl:message>
    <wsdl:portType name="DB_Select_ptt">
        <wsdl:operation name="DB_SelectSelect">
            <wsdl:input message="tns:DB_SelectSelect_inputParameters"/>
            <wsdl:output message="tns:CreditcardinfoCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
